### ISSUE TITLE
cdn2nsp - Input NSP and Output NSP differs

### ISSUE THREAD

**Issue by Immersion95** [DarkMatterCore/dom_xml_dataset_generators#11]
I wanted to try this tool with a No-intro dump of "Azure Striker GUNVOLT_ STRIKER PACK".

I first extracted the file with NSCB and processed it with cdn2nsp.

The resulting .nsp differs drastically from the No-Intro dump. Is that intended ?

**Comment by DarkMatterCore** [comment]
The No-Intro NSP dat hasn't been updated yet to accurately reflect checksums from NSPs generated by cdn2nsp.

Furthermore, the script is still lacking modified ticket serialization (e.g. tickets that were modified by certain tools other than nxdumptool need to be fixed), and I'm also working on another branch that removes the need for old hactool by using a custom hactoolnet build.

**Comment by Immersion95** [comment]
That's what I thought, thanks for all of your work :).
