### ISSUE TITLE
Suggestion: Set dump date as unconfirmed by default

### ISSUE THREAD

**Issue by mariomadproductions** [DarkMatterCore/dom_xml_dataset_generators#7]

**Comment by DarkMatterCore** [comment]
Do you know which XML property is used for this? I suppose it's `d_date_info`, but I'm currently setting it to either `0` or `1` depending on whether the dump date was provided or not.

**Comment by mariomadproductions** [comment]
Yeah, d_date_info is if the date is confirmed or not.

**Comment by DarkMatterCore** [comment]
Alright, then this is already being taken care of for both the dump and release dates.
